server {
    listen 127.0.0.1:8080;
    server_name example.com;
    location /old {
        return 301 /leen;
    }
    location /google {
        return 302 http://www.google.com;
    }

    location /error {
        return 500;
    }

    location / {
        root ./www;
        index index.html;
        autoindex on;
        methods GET DELETE;
    }

    location /cgi {
        root ./www/cgi-bin;
        methods GET POST;
        cgi_extensions .php /usr/bin/php .sh /bin/bash .py /usr/bin/python3;
    }
    location /upload {
        root ./www;
        methods POST;
        upload_path ./www/uploads;
    }
}
